"""
Create ALL Professional Legal Document Templates
Updates all templates in the DOC_TEMPLATE folder
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os

def add_border_to_section(section):
    """Add decorative border to make it look like stamp paper"""
    sectPr = section._sectPr
    pgBorders = sectPr.find(qn('w:pgBorders'))
    if pgBorders is None:
        pgBorders = OxmlElement('w:pgBorders')
        sectPr.append(pgBorders)
        pgBorders.set(qn('w:offsetFrom'), 'page')

    # Add borders with legal brown color
    for border_name in ['w:top', 'w:left', 'w:bottom', 'w:right']:
        border = OxmlElement(border_name)
        border.set(qn('w:val'), 'double')
        border.set(qn('w:sz'), '24')
        border.set(qn('w:space'), '24')
        border.set(qn('w:color'), '8B4513')  # Brown
        pgBorders.append(border)

def add_professional_header(doc):
    """Add professional header with logo"""
    section = doc.sections[0]
    header = section.header

    # Clear existing header
    for para in header.paragraphs:
        para.clear()

    header_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()

    # Add logo if exists - try new logo first, then fallback
    logo_path = "./Lawmate/Lawmate/public/lawmate-logo.png"
    if not os.path.exists(logo_path):
        logo_path = "./data/lawmate-logo.png"
    if not os.path.exists(logo_path):
        logo_path = "./Lawmate/Lawmate/public/placeholder-logo.png"

    if os.path.exists(logo_path):
        run = header_para.add_run()
        run.add_picture(logo_path, width=Inches(1.5))
        header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # App name
    header_name = header.add_paragraph()
    header_run = header_name.add_run("Lawmate - Legal Document Generation System")
    header_run.font.size = Pt(14)
    header_run.font.bold = True
    header_run.font.color.rgb = RGBColor(139, 69, 19)
    header_name.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Horizontal line
    header_line = header.add_paragraph()
    header_line_run = header_line.add_run("═" * 70)
    header_line_run.font.color.rgb = RGBColor(139, 69, 19)
    header_line.alignment = WD_ALIGN_PARAGRAPH.CENTER

def add_professional_footer(doc):
    """Add professional footer"""
    footer_section = doc.sections[0].footer

    # Clear existing footer
    for para in footer_section.paragraphs:
        para.clear()

    footer_para = footer_section.paragraphs[0] if footer_section.paragraphs else footer_section.add_paragraph()
    footer_para.text = "Generated by Lawmate | Professional Legal Document System"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.runs[0]
    footer_run.font.size = Pt(9)
    footer_run.font.italic = True
    footer_run.font.color.rgb = RGBColor(128, 128, 128)

def format_paragraph_professional(para, is_title=False, is_heading=False):
    """Apply professional formatting to paragraph"""
    for run in para.runs:
        run.font.name = 'Times New Roman'

        if is_title:
            run.font.size = Pt(16)
            run.font.bold = True
            run.font.color.rgb = RGBColor(0, 0, 0)
            run.font.underline = True
        elif is_heading:
            run.font.size = Pt(12)
            run.font.bold = True
            run.font.color.rgb = RGBColor(139, 69, 19)
        else:
            run.font.size = Pt(11)

    if is_title:
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        para.space_before = Pt(12)
        para.space_after = Pt(12)
    elif is_heading:
        para.space_before = Pt(10)
        para.space_after = Pt(6)
    else:
        para.paragraph_format.line_spacing = 1.5
        para.paragraph_format.space_after = Pt(6)
        para.paragraph_format.first_line_indent = Inches(0.3)
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

def upgrade_template(file_path):
    """Upgrade existing template to professional format"""
    print(f"\nUpgrading: {os.path.basename(file_path)}")

    try:
        doc = Document(file_path)

        # Set margins
        for section in doc.sections:
            section.top_margin = Inches(1.2)
            section.bottom_margin = Inches(1.2)
            section.left_margin = Inches(1.3)
            section.right_margin = Inches(1.3)
            add_border_to_section(section)

        # Add professional header and footer
        add_professional_header(doc)
        add_professional_footer(doc)

        # Format existing content
        for i, para in enumerate(doc.paragraphs):
            if i == 0 or 'IN THE COURT' in para.text.upper():
                format_paragraph_professional(para, is_title=True)
            elif any(keyword in para.text.upper() for keyword in ['APPLICATION FOR', 'PETITION FOR', 'PRAYER:', 'APPLICANT']):
                format_paragraph_professional(para, is_heading=True)
            else:
                format_paragraph_professional(para)

        # Save
        doc.save(file_path)
        print(f"  ✅ Upgraded successfully")
        return True

    except Exception as e:
        print(f"  ❌ Error: {e}")
        return False

# Process all templates
template_dir = "./data/DOC_TEMPLATE"
templates = [f for f in os.listdir(template_dir) if f.endswith('.docx')]

print(f"Found {len(templates)} templates to upgrade")
print("=" * 60)

success_count = 0
for template_file in templates:
    file_path = os.path.join(template_dir, template_file)
    if upgrade_template(file_path):
        success_count += 1

print("\n" + "=" * 60)
print(f"✅ Successfully upgraded {success_count}/{len(templates)} templates")
print("\nAll templates now feature:")
print("  • Professional header with Lawmate logo")
print("  • Stamp paper borders (brown double lines)")
print("  • Proper margins (1.2\" - 1.3\")")
print("  • Times New Roman font, 11pt")
print("  • 1.5 line spacing")
print("  • Justified alignment")
print("  • Color-coded headings (brown)")
print("  • Professional footer")
print("  • First-line indentation")
