"""
Create Professional Stamp Paper Style Templates
- Light brown/beige paper background
- Simple black single-line border
- User's logo
- Minimal professional formatting
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os

def add_stamp_paper_background(section):
    """Add light brown stamp paper background color"""
    sectPr = section._sectPr

    # Add background color (light brown/beige like stamp paper)
    shd = sectPr.find(qn('w:pgSz'))
    if shd is None:
        shd = OxmlElement('w:background')
        sectPr.insert(0, shd)
        # Light brown color similar to stamp paper: #F5E6D3 or #E8DCC4
        shd.set(qn('w:color'), 'F5E6D3')

def add_simple_black_border(section):
    """Add simple single black border like stamp paper"""
    sectPr = section._sectPr
    pgBorders = sectPr.find(qn('w:pgBorders'))
    if pgBorders is None:
        pgBorders = OxmlElement('w:pgBorders')
        sectPr.append(pgBorders)
        pgBorders.set(qn('w:offsetFrom'), 'page')

    # Add simple single black borders
    for border_name in ['w:top', 'w:left', 'w:bottom', 'w:right']:
        border = OxmlElement(border_name)
        border.set(qn('w:val'), 'single')  # Single line
        border.set(qn('w:sz'), '18')  # Thicker single line
        border.set(qn('w:space'), '24')  # Space from text
        border.set(qn('w:color'), '000000')  # Black color
        pgBorders.append(border)

def add_simple_header(doc, logo_path):
    """Add simple header with user's logo"""
    section = doc.sections[0]
    header = section.header

    # Clear existing header
    for para in header.paragraphs:
        para.clear()

    header_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()

    # Add user's logo if exists
    if os.path.exists(logo_path):
        try:
            run = header_para.add_run()
            run.add_picture(logo_path, width=Inches(1.8))
            header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        except Exception as e:
            print(f"  Warning: Could not add logo: {e}")

    # Add small line separator
    header_line = header.add_paragraph()
    header_line_run = header_line.add_run("_" * 80)
    header_line_run.font.size = Pt(6)
    header_line_run.font.color.rgb = RGBColor(0, 0, 0)
    header_line.alignment = WD_ALIGN_PARAGRAPH.CENTER

def add_simple_footer(doc):
    """Add minimal footer"""
    footer_section = doc.sections[0].footer

    # Clear existing footer
    for para in footer_section.paragraphs:
        para.clear()

    footer_para = footer_section.paragraphs[0] if footer_section.paragraphs else footer_section.add_paragraph()
    footer_para.text = "Generated by Lawmate"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.runs[0]
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(100, 100, 100)

def format_paragraph_simple(para, is_title=False, is_heading=False):
    """Apply simple professional formatting"""
    for run in para.runs:
        run.font.name = 'Times New Roman'
        run.font.color.rgb = RGBColor(0, 0, 0)  # Black text

        if is_title:
            run.font.size = Pt(14)
            run.font.bold = True
            run.font.underline = False  # No underline for cleaner look
        elif is_heading:
            run.font.size = Pt(12)
            run.font.bold = True
        else:
            run.font.size = Pt(11)
            run.font.bold = False

    if is_title:
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        para.space_before = Pt(6)
        para.space_after = Pt(6)
    elif is_heading:
        para.space_before = Pt(8)
        para.space_after = Pt(4)
    else:
        para.paragraph_format.line_spacing = 1.5
        para.paragraph_format.space_after = Pt(4)
        para.paragraph_format.first_line_indent = Inches(0.25)
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

def upgrade_template_stamp_paper(file_path, logo_path):
    """Upgrade template to stamp paper style"""
    print(f"\nUpgrading: {os.path.basename(file_path)}")

    try:
        doc = Document(file_path)

        # Set margins
        for section in doc.sections:
            section.top_margin = Inches(1.0)
            section.bottom_margin = Inches(1.0)
            section.left_margin = Inches(1.2)
            section.right_margin = Inches(1.2)
            # Add black single border
            add_simple_black_border(section)

        # Add header and footer
        add_simple_header(doc, logo_path)
        add_simple_footer(doc)

        # Format existing content with simple styling
        for i, para in enumerate(doc.paragraphs):
            if i == 0 or 'IN THE COURT' in para.text.upper():
                format_paragraph_simple(para, is_title=True)
            elif any(keyword in para.text.upper() for keyword in ['APPLICATION FOR', 'PETITION FOR', 'PRAYER:', 'APPLICANT', 'THROUGH COUNSEL']):
                format_paragraph_simple(para, is_heading=True)
            else:
                format_paragraph_simple(para)

        # Save
        doc.save(file_path)
        print(f"  ✅ Upgraded successfully")
        return True

    except Exception as e:
        print(f"  ❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return False

# User's logo path (converted from SVG to PNG)
user_logo_path = "./data/user-logo.png"

# Check if logo exists, fallback to default
if not os.path.exists(user_logo_path):
    print(f"Warning: Logo not found at {user_logo_path}")
    print("Will use default Lawmate logo instead")
    user_logo_path = "./data/lawmate-logo.png"

# Process all templates
template_dir = "./data/DOC_TEMPLATE"
templates = [f for f in os.listdir(template_dir) if f.endswith('.docx')]

print("=" * 70)
print("CREATING STAMP PAPER STYLE TEMPLATES")
print("=" * 70)
print(f"\nUsing logo: {user_logo_path}")
print(f"Found {len(templates)} templates to upgrade\n")

success_count = 0
for template_file in templates:
    file_path = os.path.join(template_dir, template_file)
    if upgrade_template_stamp_paper(file_path, user_logo_path):
        success_count += 1

print("\n" + "=" * 70)
print(f"✅ Successfully upgraded {success_count}/{len(templates)} templates")
print("\n📄 Stamp Paper Features:")
print("  • Light brown/beige paper background (like real stamp paper)")
print("  • Simple black single-line border")
print("  • Your custom logo in header")
print("  • Minimal professional formatting")
print("  • Times New Roman, 11pt body text")
print("  • Bold headings only where needed")
print("  • Clean and professional appearance")
print("=" * 70)
